project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "AI Training 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



