project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Essential Prompting Techniques"
  navbar:
    left:
      - href: index.qmd
        text: Main
      # - about.qmd
      - href: pretraining.qmd
        text: Pretraining


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



